### ISSUE TITLE
No parsing?

### ISSUE THREAD

**Issue by RiccardoPizzutti** [GRAAL-Research/deepparse#125]
Hey guys, 

i installed deepparse on a SageMaker Studio instance. Then i tried this: 

from deepparse.parser import AddressParser
address_parser = AddressParser(model_type="bpemb", device=0)
parsed_address = address_parser("Moltkestrasse 27 50674 Köln")
print(parsed_address)

The result is just the parsed string "Moltkestrasse 27 50674 Köln" no errors etc. 

Is that a bug? 

Thank you very much for your efforts!

**Comment by MAYAS3** [comment]
Hello @RiccardoPizzutti,

That's actually normal because printing a FormattedParsedAddress directly only prints the string representation of the address itself. If you wish to obtain the parsing, try running the following:

```python
from deepparse.parser import AddressParser
address_parser = AddressParser(model_type="bpemb", device=0)
parsed_address = address_parser("Moltkestrasse 27 50674 Köln")

print(parsed_address.parsed_address_components)

```

You can check out the [docs](https://deepparse.org/parser.html#formatted-parsed-address) for more details. 

Thanks for your interest in deepparse!

Let me know if you have any further questions or comments!

**Comment by RiccardoPizzutti** [comment]
Thank you so much Marouane!! You had a little typo in the (parsed_address_components => address_parsed_components) but I figured out with the docs. 

Thanks again and all the best
Maik
