### ISSUE TITLE
Retrain an Address Parser for Single Country Uses

### ISSUE THREAD

**Issue by tapiatellez** [GRAAL-Research/deepparse#166]
**Describe the bug**
While going through the "Retrain an Address Parser for Single Country Uses" process I was trying to retrain the model for Mexico's only usage and everything was going well until I was testing the address_parser object with the test_container data.

**To Reproduce**
# Import the train and test datasets into memory to retrain our parser model
clean_root_dir = os.path.join(root_dir, "clean_data")
clean_train_directory = os.path.join(clean_root_dir, "train")
clean_test_directory = os.path.join(clean_root_dir, "test")

mx_training_data_path = os.path.join(clean_train_directory, "mx.p")
mx_test_data_path = os.path.join(clean_test_directory, "mx.p")

training_container = PickleDatasetContainer(mx_training_data_path)
test_container = PickleDatasetContainer(mx_test_data_path)

address_parser = AddressParser(model_type="fasttext", device=0)

address_parser.test(test_container, batch_size=256)

**Expected behavior**
I expected to obtain the test results for the test_container Mexican dataset. 

**Screenshots**
![Screen Shot 2022-11-08 at 20 14 09](https://user-images.githubusercontent.com/13044100/200720480-1cf5cc64-6cd4-4bb7-bffa-9a5fda2ee29b.png)
the problem here.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version version 11.6

**Comment by MAYAS3** [comment]
Hello @tapiatellez,

This seems to be a multiprocessing issue related to PyTorch's Dataloader. When using **deepparse**'s `retrain()` and `test()` you can specify the number of subprocesses used to load the data via a Dataloder. However, in macOS and Windows, the *spawn* method is used by default to initialise the subprocesses. As opposed to the *fork* starting method, which is the default in Linux, *spawned* processes do not share memory with the parent process, but each have a pickled copy of the parent's memory. This causes an issue with the `fasttext` parser since the fastText package contains C++ code which cannot be pickled.

To solve the issue you can either pass `num_workers=0` to the `retrain()` and `test()` methods, or since you're running macOS you can switch to a *fork* start method by calling `torch.multiprocessing.set_start_method('fork')` once before calling the aforementioned methods. Unfortunately, this wouldn't work on Windows since it does not have support for *fork*.

I'll try to provide a fix as soon as possible. In the mean time, could you let me know if the solutions I've proposed work for you?

**Comment by tapiatellez** [comment]
Hello @MAYAS3 

Thank you for your response. I tried the `num_worders=0` solution on the `test()` function and it worked and returned the following results:
<img width="1131" alt="Screen Shot 2022-11-14 at 13 46 36" src="https://user-images.githubusercontent.com/13044100/201751718-ce9b80c4-2f5d-49d6-8490-550c4894cc3c.png">

I then proceeded to train the model using the `train()`function but the `num_workers=0` solution did not work and returned the following error:
<img width="929" alt="Screen Shot 2022-11-14 at 13 52 11" src="https://user-images.githubusercontent.com/13044100/201752798-f3fdabd1-69ea-43c7-95db-0df58c96e614.png">
Since the `num_workers=0`solution did not work  I tried switching to a fork start method by calling `torch.multiprocessing.set_start_method('fork')` before calling the `train()`method but I got the following error:
<img width="925" alt="Screen Shot 2022-11-14 at 13 57 34" src="https://user-images.githubusercontent.com/13044100/201753847-543c244b-3aa8-4b6c-b00d-56b5a1a633a6.png">

Could you be so kind to help me with this problem? Thank you very much in advance and hope to hear from you soon. 

Cheers.

**Comment by davebulaval** [comment]
Change `0.8` to `train_ratio=0.8`. We have changed the interface to add a `val_container,` and as I can see, this example was not updated. Thank you for bringing this bug to our attention. I will fix it.

**Comment by tapiatellez** [comment]
Thank you so much, I was able to train the model for single-country purposes only.
