### ISSUE TITLE
[BUG] 404 Client Error: Not Found for url: https://bpemb.h-its.org/multi/multi.wiki.bpe.vs100000.model

### ISSUE THREAD

**Issue by ajndkr** [GRAAL-Research/deepparse#217]
**Describe the bug**

`AddressParser` fails due to incorrect model path: https://bpemb.h-its.org/multi/multi.wiki.bpe.vs100000.model

**To Reproduce**

```
from deepparse.parser import AddressParser
address_parser = AddressParser(model_type="bpemb", device=0)
```

**Expected behavior**

I believe the class needs to download the model from the following url: https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs1000000.model

**Comment by davebulaval** [comment]
Yeah, it appears they have changed the URL from [https://bpemb.h-its.org/multi/multi.wiki.bpe.vs100000.model](https://bpemb.h-its.org/multi/multi.wiki.bpe.vs100000.model) to [https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs1000000.model](https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs1000000.model). The problem is not ours but BPEmb library.

It seems like an involuntary error on their side. I have opened an issue on the project repo [here](https://github.com/bheinzerling/bpemb/issues/68#issue-2191074577).

**Comment by akseljoonas** [comment]
Is there a fix or is the `AddressParser` unusable for now?

**Comment by ajndkr** [comment]
@akseljoonas for the time being, until it is resolved on bpemb side, you can use this workaround. 


```
mkdir -p ~/.cache/deepparse/multi/ && \
          wget -O ~/.cache/deepparse/multi/multi.wiki.bpe.vs100000.model https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs100000.model && \
          wget -O multi.wiki.bpe.vs100000.d300.w2v.bin.tar.gz https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs100000.d300.w2v.bin.tar.gz && \
          tar -xzf multi.wiki.bpe.vs100000.d300.w2v.bin.tar.gz -C ~/.cache/deepparse/multi/ && rm multi.wiki.bpe.vs100000.d300.w2v.bin.tar.gz
```

I download these files into the cache folder before initialising `AddressParser`.

**Comment by davebulaval** [comment]
> Is there a fix or is the `AddressParser` with bpemb unusable for now?

No, except for the @ajndkr solution.
