### ISSUE TITLE
FYI: I'm trying a spaCy-based method

### ISSUE THREAD

**Issue by NickCrews** [GRAAL-Research/deepparse#237]
Hi! 

[I have been playing](https://github.com/NickCrews/spacy-address) with using the NER functionalities of spaCy to do something very similar to your effort here.

I am managing to achieve:

- F1 score for NER of .978
- model size of ~5MB
- on my 2021 M1 MacBook Pro, tags 1000 addresses in ~.2 sec

which I was fairly impressed by after only tinkering for only a day. A few thoughts/questions:

- I was really impressed with the developer experience of using spaCy. They really set me up for success here. Potentially you might want to see how they are doing things, there might be something there. Perhaps you could build on top of their framework? Users then get a nice familiar API too.
- I wanted to follow the USPS standard for tagging. It looks like your dataset is a little different? Which really is bummer, I'd love to use it! Do you know of any datasets that follow the USPS standard? I have been using the data from [usaddress](https://github.com/datamade/usaddress/tree/main/training)
- If there is anything else you want to chat about, I'd love to work together on this!

**Comment by davebulaval** [comment]
1. The difference is the model size, and we will only put so much effort into the library since we have other projects we work on. Our objective was to offer flexibility with our framework, and since the initial release, much has changed in the deep learning ecosystem (e.g., HuggingFace Hub). 
Our goal was more academic to see what the domain adoption possibilities are.
2. No, sorry.
3. we have a discussion zone for people to discuss if you want to start discussing something.

**Comment by NickCrews** [comment]
Thanks! Just wanted to get it on your radar, but yeah there's not anything concrete I'm looking for here so I'll close it out. Appreciate your work here!

**Comment by davebulaval** [comment]
But if you want to propose a PR that leverages the SpaCy framework, we are open to it.
