### ISSUE TITLE
LGPL licence

### ISSUE THREAD

**Issue by etiennebr** [GRAAL-Research/deepparse#65]
I'd like to contribute to the project, but the LGPL license is quite restrictive because all derivatives can only be redistributed under LGPL v3 license (as I understand it). I'm not sure it is a complete blocker, but it might be an issue down the road. Would you consider relicensing the project under a slightly more permissible license, such as GPL or MIT (or another)?

**Comment by freud14** [comment]
Hi @etiennebr, while I am not one of the main developers of the project, let me just weigh in on why I think the LGPL is a good license for this project. 

One important concept to understand in licensing is the concept of distribution. For most open source licenses to apply, the software has to be distributed in some way. For instance, selling the software is distribution. Giving it as a download on a website is distribution. However, using it inside a company is not distribution. With the exception of the AGPL license, using it as a back-end of a website is also not distribution.

Since you suggested it, I would like to say that the GPL license is a more restrictive license than the LGPL. Indeed, any codebase using a library licensed under GPL must be distributed under the same GPL license whereas that is not the case with an LGPL-licensed library. The main restriction of the LGPL license (and of the GPL license) is that modifications to LGPL-licensed code should be distributed under the same LGPL license. Thus, a project wanting to use a library under an LGPL license only has to distribute its software with the source code of the used LGPL-licensed library. I hope this clears up the difference between the GPL and LGPL licenses.

I think that the LGPL license is a better compromise between the more restrictive GPL license and less restrictive licenses such as the MIT license you mentioned. Indeed, the LGPL ensures that any modifications to the codebase of the library are shared to the community while allowing other projects to use it without having the whole projects having to be under the LGPL license.

Let me know if you have questions on what I wrote. I hope I was clear.

Thank you.

**Comment by davebulaval** [comment]
> I'd like to contribute to the project, but the LGPL license is quite restrictive because all derivatives can only be redistributed under LGPL v3 license (as I understand it). I'm not sure it is a complete blocker, but it might be an issue down the road. Would you consider relicensing the project under a slightly more permissible license, such as GPL or MIT (or another)?

What type of issue do you have in mind?

**Comment by davebulaval** [comment]
> Hi @etiennebr, while I am not one of the main developers of the project, let me just weigh in on why I think the LGPL is a good license for this project.
> 
> One important concept to understand in licensing is the concept of distribution. For most open source licenses to apply, the software has to be distributed in some way. For instance, selling the software is distribution. Giving it as a download on a website is distribution. However, using it inside a company is not distribution. With the exception of the AGPL license, using it as a back-end of a website is also not distribution.
> 
> Since you suggested it, I would like to say that the GPL license is a more restrictive license than the LGPL. Indeed, any codebase using a library licensed under GPL must be distributed under the same GPL license whereas that is not the case with an LGPL-licensed library. The main restriction of the LGPL license (and of the GPL license) is that modifications to LGPL-licensed code should be distributed under the same LGPL license. Thus, a project wanting to use a library under an LGPL license only has to distribute its software with the source code of the used LGPL-licensed library. I hope this clears up the difference between the GPL and LGPL licenses.
> 
> I think that the LGPL license is a better compromise between the more restrictive GPL license and less restrictive licenses such as the MIT license you mentioned. Indeed, the LGPL ensures that any modifications to the codebase of the library are shared to the community while allowing other projects to use it without having the whole projects having to be under the LGPL license.
> 
> Let me know if you have questions on what I wrote. I hope I was clear.
> 
> Thank you.

From my understanding, a person/cie can use the software as he wants, but if he modifies our codebase, he needs to opensource the code?

**Comment by freud14** [comment]
> From my understanding, a person/cie can use the software as he wants, but if he modifies our codebase, he needs to opensource the code?

Yes but only if the software is distributed, hence my paragraph on what constitutes distribution.

**Comment by etiennebr** [comment]
Thanks @freud14, I'm really out of my comfort zone here, so thanks for the clarification. My first issue is that the legal approval is not as straightforward as MIT, for example. So I'll see how it turns out with the lawyers and get back to you if it still poses an issue.
